platform :ios, '15.0'
use_frameworks!
inhibit_all_warnings!

target 'App' do
  pod 'Capacitor', '~> 8.0'
  pod 'CapacitorCordova', '~> 8.0'
  pod 'CapacitorCommunitySpeechRecognition', :path => '../../node_modules/@capacitor-community/speech-recognition'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
